[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:django]
directory=/project/
command=/entrypoint.sh
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:huey]
directory=/project/
environment=HUEY="True"
command=/entrypoint.sh
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[group:all]
programs=django,huey
