# Generated by Django 3.2.10 on 2023-07-30 06:06

import django.contrib.postgres.fields
from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freeradius', '0008_alter_device_import_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MosyleIntegrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('info_messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessToken', fernet_fields.fields.EncryptedTextField()),
                ('username', models.CharField(max_length=255)),
                ('password', fernet_fields.fields.EncryptedTextField()),
                ('apiURL', models.CharField(default='https://managerapi.mosyle.com/v2', max_length=255)),
                ('devices', models.ManyToManyField(blank=True, null=True, to='freeradius.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
