# Generated by Django 3.2.10 on 2025-02-05 16:10

import django.contrib.postgres.fields
from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('freeradius', '0008_alter_device_import_source'),
        ('integrations', '0002_auto_20250205_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('info_messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('service_account', fernet_fields.fields.EncryptedTextField()),
                ('devices', models.ManyToManyField(blank=True, null=True, to='freeradius.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GoogleIntegraion',
        ),
    ]
