# Generated by Django 3.2.10 on 2022-02-18 21:25

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mac', macaddress.fields.MACAddressField(integer=True, primary_key=True, serialize=False, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=253, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('import_source', models.CharField(choices=[('MN', 'Manual'), ('AP', 'API'), ('CV', 'CSV')], default='MN', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
