# Generated by Django 3.2.10 on 2022-02-23 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeradius', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImporter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manual_upload', models.BooleanField(default=True)),
                ('findings_csv', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('overwrite', models.BooleanField(default=True, help_text='Overwrite existing hostname & description?')),
                ('mac_header', models.CharField(default='mac', max_length=254)),
                ('hostname_header', models.CharField(blank=True, max_length=254, null=True)),
                ('description_header', models.CharField(blank=True, max_length=254, null=True)),
                ('error_messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('devices', models.ManyToManyField(blank=True, null=True, to='freeradius.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
