# Generated by Django 3.2.10 on 2022-03-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeradius', '0003_rename_findings_csv_csvimporter_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimporter',
            name='overwrite',
            field=models.BooleanField(default=True),
        ),
    ]
