# Generated by Django 3.2.10 on 2022-03-04 17:30

from django.db import migrations
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('freeradius', '0003_rename_findings_csv_csvimporter_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=macaddress.fields.MACAddressField(integer=False, max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
