# Generated by Django 3.2.10 on 2022-03-04 22:46

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('freeradius', '0004_alter_device_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=netfields.fields.MACAddressField(primary_key=True, serialize=False, unique=True),
        ),
    ]
