# Generated by Django 3.2.10 on 2022-03-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeradius', '0004_alter_csvimporter_overwrite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAuthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=64)),
                ('packet_type', models.CharField(max_length=32)),
                ('called_station_id', models.CharField(blank=True, max_length=50, null=True)),
                ('calling_station_id', models.CharField(blank=True, max_length=50, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=254, null=True)),
                ('datetime', models.DateTimeField()),
                ('reject_cause', models.TextField(blank=True, null=True)),
                ('vlan_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
