# Generated by Django 3.2.10 on 2022-03-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeradius', '0005_postauthlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postauthlog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
