# Generated by Django 3.2.10 on 2022-03-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeradius', '0006_alter_postauthlog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postauthlog',
            name='trusted_device',
            field=models.BooleanField(default=False),
        ),
    ]
