# Generated by Django 3.2.10 on 2023-07-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeradius', '0007_postauthlog_trusted_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='import_source',
            field=models.CharField(choices=[('MN', 'Manual'), ('AP', 'API'), ('CV', 'CSV'), ('IN', 'Integration')], default='MN', max_length=2),
        ),
    ]
