"""
Django settings for radius-admin project.

Generated by 'django-admin startproject' using Django 2.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import saml2
import saml2.saml

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'se1)k6cz@9v1k-(%n8is!i))v&9vx11#hv7p=%*u009%)c8+y)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ['DEBUG'] == 'True'

# URL Settings
DOMAIN = os.environ.get('DOMAIN', '127.0.0.1')
WEB_PROTOCOL = os.environ.get('WEB_PROTOCOL', 'http').lower()

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'rest_framework.authtoken',
    'djangosaml2',
    'crispy_forms',
    'core',
    'freeradius',
    'ui',
    'api',
    'drf_spectacular',
    'bootstrap_modal_forms',
    'huey.contrib.djhuey',
    #'dynamic_preferences',
    # comment the following line if you don't want to use user preferences
    #'dynamic_preferences.users.apps.UserPreferencesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'djangosaml2.middleware.SamlSessionMiddleware',
]

## SAML Config O.o

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'djangosaml2.backends.Saml2Backend',
)

SAML_CONFIG = {
  # full path to the xmlsec1 binary programm
  'xmlsec_binary': '/usr/bin/xmlsec1',

  # your entity id, usually your subdomain plus the url to the metadata view
  'entityid': WEB_PROTOCOL + '://' + DOMAIN + '/saml2/metadata/',

  # directory with attribute mapping
  'attribute_map_dir': os.path.join(BASE_DIR, 'attributemaps'),

  # this block states what services we provide
  'service': {
      # we are just a lonely SP
      'sp' : {
          'name': 'FreeRADIUS Admin',
          'name_id_format': (os.environ.get('SAML_NAMEID_FORMAT', "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress")),

          # For Okta add signed logout requets. Enable this:
          # "logout_requests_signed": True,

          'endpoints': {
              # url and binding to the assetion consumer service view
              # do not change the binding or service name
              'assertion_consumer_service': [
                  (WEB_PROTOCOL + '://' + DOMAIN + '/saml2/acs/',
                   saml2.BINDING_HTTP_POST),
                  ],
              # url and binding to the single logout service view
              # do not change the binding or service name
              'single_logout_service': [
                  # Disable next two lines for HTTP_REDIRECT for IDP's that only support HTTP_POST. Ex. Okta:
                  (WEB_PROTOCOL + '://' + DOMAIN + '/saml2/ls/',
                   saml2.BINDING_HTTP_REDIRECT),
                  (WEB_PROTOCOL + '://' + DOMAIN + '/saml2/ls/post',
                   saml2.BINDING_HTTP_POST),
                  ],
              },
           # Mandates that the identity provider MUST authenticate the
           # presenter directly rather than rely on a previous security context.
          'force_authn': False,

           # Enable AllowCreate in NameIDPolicy.
          'name_id_format_allow_create': False,

          # attributes that this project need to identify a user
          #'required_attributes': ['uid'],

          # attributes that may be useful to have but not required
          #'optional_attributes': ['eduPersonAffiliation'],
          },
      },

  # where the remote metadata is stored, local, remote or mdq server.
  # One metadatastore or many ...
  'metadata': {
      'remote': [{"url": os.environ.get('SAML_IDP_METADATA_URL', ''),
                  "disable_ssl_certificate_validation": True},]
      },

  # set to 1 to output debugging information
  'debug': 1,

  # Signing
  #'key_file': os.path.join(BASE_DIR, 'private.key'),  # private part
  #'cert_file': os.path.join(BASE_DIR, 'public.pem'),  # public part

  # Encryption
  #'encryption_keypairs': [{
  #    'key_file': os.path.join(BASE_DIR, 'private.key'),  # private part
  #    'cert_file': os.path.join(BASE_DIR, 'public.pem'),  # public part
  #}],

  # own metadata settings
  'contact_person': [
      {'given_name': os.environ.get('SAML_CONTACT_FIRST_NAME', ''),
       'sur_name': os.environ.get('SAML_CONTACT_LAST_NAME', ''),
       'company': os.environ.get('SAML_CONTACT_COMPANY', ''),
       'email_address': os.environ.get('SAML_CONTACT_EMAIL', ''),
       'contact_type': 'technical'},
      ],
  # you can set multilanguage information here
  'organization': {
      'name': [(os.environ.get('SAML_COMPANY_NAME', ''), 'en')],
      'display_name': [(os.environ.get('SAML_COMPANY_DISPLAY_NAME', ''), 'en')],
      'url': [(os.environ.get('SAML_COMPANY_URL', ''), 'en')],
      },
  }

SAML_DJANGO_USER_MAIN_ATTRIBUTE = 'email'
SAML_DJANGO_USER_MAIN_ATTRIBUTE_LOOKUP = '__iexact'
SAML_USE_NAME_ID_AS_USERNAME = True

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

ROOT_URLCONF = 'radius_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'radius_admin.wsgi.application'

# Caches
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get('REDIS_CACHE_URL', 'redis://redis:6379/0'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "default"

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PWD', 'postgres'),
        'HOST': 'db',
        'PORT': 5432,
    }
}

# Update User References
AUTH_USER_MODEL = 'core.User'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR,STATIC_ROOT,'media')

STATIC_URL = '/static/'

# Django REST

REST_FRAMEWORK = {
   'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
   'DEFAULT_AUTHENTICATION_CLASSES': (
       'rest_framework.authentication.SessionAuthentication',
       'rest_framework.authentication.BasicAuthentication',
       'rest_framework.authentication.TokenAuthentication',
   ),
   'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
   ),
   'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
   'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
   'PAGE_SIZE': 100
}


SPECTACULAR_SETTINGS = {
    'SERVE_PUBLIC': False,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAuthenticated'],
    'TITLE': 'FreeRADIUS Admin API',
    'CONTACT': {
        'name': "ESU2 Technology",
        'url': "https://www.esu2.org/",
    },
    'VERSION': '0.0.1',
}

# Huey Task Queue Settings
HUEY = {
    'huey_class': 'huey.RedisHuey',  # Huey implementation to use.
    'results': True,  # Store return values of tasks.
    'store_none': False,  # If a task returns None, do not save to results.
    'immediate': False,
    'blocking': True,  # Perform blocking pop rather than poll Redis.
    'connection': {
        'url': os.environ.get('REDIS_HUEY_URL', 'redis://redis:6379/1'),
    },
    'consumer': {
        'workers': 2,
        'worker_type': 'thread',
    },
}
